### ISSUE TITLE
[FR] generate sdist that wont need cython

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [joshua-auchincloss/hatch-cython#21]
projects like borgbacup that for various reasons can't ship manylinux wheels (like the need for libs outside of manylinux)
it would be neat if it was possible to create a sdist that does not need cython to build

this may need upstream work in hatch for enablement

**Comment by joshua-auchincloss** [comment]
> projects like borgbacup that for various reasons can't ship manylinux wheels (like the need for libs outside of manylinux)
> 
> it would be neat if it was possible to create a sdist that does not need cython to build
> 
> 
> 
> this may need upstream work in hatch for enablement

Good idea, this wouldn't be too difficult IMO - I think the plug-in could be adapted for sdist to compile (cython) & package the c/cpp headers. I took a quick look at the [setup.py](https://github.com/borgbackup/borg/blob/master/setup.py) for borg & that appears to be the approach used.

Will add as test feature in next release

**Comment by joshua-auchincloss** [comment]
Hey @RonnyPfannschmidt, a few thoughts about this - 
I've gone ahead and done some testing & in theory, the c/cpp files can be generated & e.g. separated within sublevels with a bootstrap `setup.py`. Where I think this gets messy is that this plugin supports multiple platform & arch specific filters on e.g. flags, templated kwargs, etc. So, since `pip install xxxlib` already installs `hatch-cython` if it is defined in build-dependencies, & thus `Cython`. As such, during sdist builds it seems redundant to add this in when the arguments are already passed both to Cython & the c/++ compiler. I would say it is more ideal to leave the raw source files in the sdist, and allow the target platform to follow the platform & arch disposition through this plugin. A similar feature I may add instead, is the ability to perform platform & arch specific file ignores. Thus, at build time the writer may optionally compile e.g. windows vs linux specific files. From my understanding of the project used as an example, this would have a more consistent effect than playing with the sdist. Let me know your thoughts, I'll keep this open for a bit in case someone stumbles on this & has differing opinions

**Comment by RonnyPfannschmidt** [comment]
The primary details for this idea is to reduce the build dependency closure for packagers 

It's indeed a bit contrary to build time conditions
